server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: elekberovk442@gmail.com
    password: flaqxrysijyqfbhd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
